### ISSUE TITLE
Why are merge_flat() and merge_mixed() undocumented?

### ISSUE THREAD

**Issue by bpj** [miyagawa/Hash-MultiValue#12]
Why are merge_flat() and merge_mixed() undocumented?

**Comment by miyagawa** [comment]
They're considered internal methods and you're supposed to use `new` or `from_mixed` instead.

**Comment by miyagawa** [comment]
If there's a use case for these as an instance method, a doc patch would be great.

**Comment by bpj** [comment]
I do have a use case: A HMV object which can't/shouldn't be replaced by another because it is embedded in another object, since I do want to keep it readonly, into which data for several keys should be merged at once, from another HMV object even.

``` perl
$my_obj->hmv->merge_flat( $other_obj->hmv->flatten );
```

as opposed to

``` perl
$my_obj->hmv( 
    Hash::MultiValue->new( $my_obj->hmv->flatten, $other_obj->hmv->flatten)
);
```

Sure I could add a method wrapping that, which would still require making the "hmv" accessor rw, or some kind of loop calling add() repeatedly, but that seems a waste when those other methods are there.

Is that enough of a use case?

**Comment by miyagawa** [comment]
Not sure if I follow: there's an `add` method already, so you can always do:

``` perl
$other_obj->hmv->each(sub { $my_obj->hmv->add(@_) });
```
